<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>equochromium</groupId>
	<artifactId>samples-parent</artifactId>
	<packaging>pom</packaging>
	<version>1.0-SNAPSHOT</version>

	<properties>
		<chromium.version>150.0.1</chromium.version>
		<chromium.platform.version>150.0.1</chromium.platform.version>
	</properties>

	<modules>
		<module>swt</module>
		<module>standalone</module>
		<module>swing</module>
		<module>javafx</module>
	</modules>
</project>
