<?xml version="1.0" encoding="UTF-8"?>
<project
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"
    xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <modelVersion>4.0.0</modelVersion>
    <groupId>equochromium</groupId>
    <artifactId>rcp</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <properties>
        <maven.exec.phase>none</maven.exec.phase>
        <productModule>sample.product</productModule>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.eclipse.tycho</groupId>
                <artifactId>tycho-p2-director-plugin</artifactId>
                <version>${tycho-version}</version>
                <executions>
                    <execution>
                        <id>materialize-products</id>
                        <goals>
                            <goal>materialize-products</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>archive-products</id>
                        <goals>
                            <goal>archive-products</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.eclipse.tycho</groupId>
                <artifactId>tycho-maven-plugin</artifactId>
                <version>${tycho-version}</version>
                <extensions>true</extensions>
            </plugin>
            <plugin>
                <groupId>org.eclipse.tycho</groupId>
                <artifactId>target-platform-configuration</artifactId>
                <version>${tycho-version}</version>
                <configuration>
                    <target>
                        <file>../sample.rcp.target</file>
                    </target>
                    <environments>
                        <environment>
                            <os>linux</os>
                            <ws>gtk</ws>
                            <arch>x86_64</arch>
                        </environment>
                        <environment>
                            <os>linux</os>
                            <ws>gtk</ws>
                            <arch>aarch64</arch>
                        </environment>
                        <environment>
                            <os>win32</os>
                            <ws>win32</ws>
                            <arch>x86_64</arch>
                        </environment>
                        <environment>
                            <os>win32</os>
                            <ws>win32</ws>
                            <arch>aarch64</arch>
                        </environment>
                        <environment>
                            <os>macosx</os>
                            <ws>cocoa</ws>
                            <arch>x86_64</arch>
                        </environment>
                        <environment>
                            <os>macosx</os>
                            <ws>cocoa</ws>
                            <arch>aarch64</arch>
                        </environment>
                    </environments>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>3.1.0</version>
                <executions>
                    <execution>
                        <phase>${maven.exec.phase}</phase>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <executable>${executable}</executable>
                    <workingDirectory>${project.basedir}/${productModule}/target/products/ChromiumRCP</workingDirectory>
                </configuration>
            </plugin>
            <plugin>
                <artifactId>maven-clean-plugin</artifactId>
                <configuration>
                    <filesets>
                        <fileset>
                            <directory>${project.basedir}/sample.rcp/target</directory>
                        </fileset>
                        <fileset>
                            <directory>${project.basedir}/sample.product/target</directory>
                        </fileset>
                        <fileset>
                            <directory>${project.basedir}/sample.product.mac/target</directory>
                        </fileset>
                        <fileset>
                            <directory>${project.basedir}/sample.product.win/target</directory>
                        </fileset>
                        <fileset>
                            <directory>${project.basedir}/sample.product.linux/target</directory>
                        </fileset>
                    </filesets>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>build</id>
            <activation>
                <property>
                    <name>!run</name>
                </property>
            </activation>
            <modules>
                <module>sample.rcp</module>
                <module>${productModule}</module>
            </modules>
        </profile>
        <profile>
            <id>exec</id>
            <activation>
                <os>
                    <family>linux</family>
                </os>
                <property>
                    <name>run</name>
                </property>
            </activation>
            <properties>
                <maven.exec.phase>verify</maven.exec.phase>
                <executable>./linux/gtk/${os.arch}/ChromiumRCP</executable>
            </properties>
        </profile>
        <profile>
            <id>windows</id>
            <activation>
                <os>
                    <family>windows</family>
                </os>
                <property>
                    <name>run</name>
                </property>
            </activation>
            <properties>
                <maven.exec.phase>verify</maven.exec.phase>
                <executable>win32/win32/${os.arch}/ChromiumRCP</executable>
            </properties>
        </profile>
        <profile>
            <id>mac</id>
            <activation>
                <os>
                    <family>mac</family>
                </os>
                <property>
                    <name>run</name>
                </property>
            </activation>
            <properties>
                <maven.exec.phase>verify</maven.exec.phase>
                <executable>macosx/cocoa/${os.arch}/Eclipse.app/Contents/MacOS/ChromiumRCP</executable>
            </properties>
        </profile>
        <profile>
			<id>amd64</id>
			<activation>
				<os>
					<arch>amd64</arch>
				</os>
			</activation>
			<properties>
				<os.arch>x86_64</os.arch>
			</properties>
		</profile>
        <profile>
            <id>platform-mac</id>
            <activation>
                <property>
                    <name>platform</name>
                    <value>mac</value>
                </property>
            </activation>
            <properties>
                <productModule>sample.product.mac</productModule>
            </properties>
        </profile>
        <profile>
            <id>platform-win</id>
            <activation>
                <property>
                    <name>platform</name>
                    <value>win</value>
                </property>
            </activation>
            <properties>
                <productModule>sample.product.win</productModule>
            </properties>
        </profile>
        <profile>
            <id>platform-linux</id>
            <activation>
                <property>
                    <name>platform</name>
                    <value>linux</value>
                </property>
            </activation>
            <properties>
                <productModule>sample.product.linux</productModule>
            </properties>
        </profile>
    </profiles>
</project>